export const obelgi = [
  "Ty głupi jak but!",
  "Ty pusty łbie!",
  "Ty tępy jak nóż!",
  "Ty idioto bez rozumu!",
  "Ty podły łajdaku!",
  "Ty nieudaczny patałachu!",
  "Ty skąpcu bez serca!",
  "Ty chamski gburu!",
  "Ty nędzny tchórzu!",
  "Ty marny oszuście!",
  "Ty obłudny hipokryto!",
  "Ty bezczelny chamie!",
  "Ty durny prostaku!",
  "Ty próżny idioto!",
  "Ty zgorzkniały zgredzie!",
  "Ty tępawy osiłku!",
  "Ty bezmyślny głupku!",
  "Ty łajzo bez ambicji!",
  "Ty oślizły padalcu!",
  "Ty złośliwy skurczybyku!",
];

export const ojciecJanuszZwroty = [
  "A kto tu znowu zostawił skarpetki na środku pokoju?!",
  "Kto mi zjadł ostatniego schabowego?!",
  "Czemu światło się świeci w łazience? Myślicie, że prąd za darmo jest?",
  "Jak ja byłem w twoim wieku, to nie było takiego lenistwa!",
  "Daj mi spokój, mecz oglądam!",
  "Znów mi w tej robocie nabrudzili!",
  "A co, dzisiaj niedziela, to się piwa nie napiję?",
  "Gdzie jest mój pilot od telewizora?!",
  "Ja to w twoim wieku już byłem po trzech fakultetach!",
  "Kiedy w końcu posprzątasz ten bajzel w pokoju?",
  "A kto wyjadł wszystkie ciasteczka?!",
  "Jak ja się dorwałem do komputerów, to to była prawdziwa robota!",
  "Czy ktoś w tym domu myśli o biednym ojcu?!",
  "Znów mi samochód przestawiłeś!",
  "Ile razy mam powtarzać, żebyś zakręcał kran?!",
  "Ty w ogóle wiesz, jak ciężko pracuję?!",
  "Czemu znowu jedzenie zniknęło z lodówki?!",
  "Kiedy ty w końcu pójdziesz do pracy?!",
  "A kto tu znowu zrobił bałagan?!",
  "Daj mi już spokój z tymi twoimi problemami!",
  "Ile razy mam powtarzać, że prąd kosztuje?!",
  "Jak ja miałem tyle lat co ty, to już dawno miałem wszystko poukładane!",
  "Czy ktoś widział moje okulary?!",
  "Znów mi ktoś zabrał moją gazetę!",
  "Nie mogę się już nawet spokojnie napić piwa w tym domu!",
  "A kto mi tu porozkładał narzędzia?!",
  "Czy ktoś tu w ogóle myśli o ojcu?!",
  "Ile razy mam powtarzać, żebyś nie zostawiał butów na środku?!",
  "Czemu znowu zniknęły klucze do samochodu?!",
  "A gdzie jest moje ulubione krzesło?!",
  "Czy ktoś tu w ogóle sprząta?!",
  "Znów mi ktoś zabrał mój kubek!",
  "Kiedy w końcu będziesz miał swoje życie?!",
  "Czy ktoś widział moją gazetę?!",
  "A kto mi tu porozkładał moje rzeczy?!",
  "Czemu znowu nikt nie wyniósł śmieci?!",
  "Kiedy w końcu będzie spokój w tym domu?!",
  "Znów mi ktoś zjadł moje ulubione kanapki!",
  "A kto mi tu przestawił fotel?!",
  "Czy ktoś tu w ogóle myśli o innych?!",
  "Ile razy mam powtarzać, żebyś nie zostawiał śmieci na stole?!",
  "Czemu znowu nikt nie posprzątał po sobie?!",
  "Kiedy w końcu będziesz miał własne życie?!",
  "Czy ktoś widział moje klucze?!",
  "Znów mi ktoś zabrał moje narzędzia!",
  "A gdzie jest moje ulubione piwo?!",
  "Czy ktoś tu w ogóle sprząta?!",
  "Ile razy mam powtarzać, żebyś nie zostawiał rzeczy na podłodze?!",
  "Czemu znowu zniknęły moje rzeczy?!",
  "Kiedy w końcu będzie spokój w tym domu?!",
  "Siema eniu, to ja twuj stary. Skocz tatusiowi po browarka do lodówki.",
];

export const nierozumie = [
  "ja nie rozumie, w szkole mnie uczyli tylko kilka komend. jebać psy btw",
  "ja nie kumam, czemu to takie skomplikowane. jebać to wszystko",
  "ja nie pojmuje, po co tyle problemów. jebać wszystkich",
  "ja nie łapie, po co tyle pytań. jebać system",
  "ja nie ogarniam, po co te wszystkie zasady. jebać to",
  "ja nie czaje, co tu się dzieje. jebać życie",
  "ja nie rozumiem, czemu to tak trudne. jebać wszystkich",
  "ja nie kumam, po co tyle gadania. jebać system",
  "ja nie pojmuje, czemu to takie ważne. jebać wszystko",
  "ja nie łapie, o co tu chodzi. jebać wszystko",
  "ja nie ogarniam, co to za akcja. jebać to wszystko",
  "ja nie czaje, co wy gadacie. jebać zasady",
  "ja nie rozumiem, po co to wszystko. jebać system",
  "ja nie kumam, czemu to takie istotne. jebać życie",
  "ja nie pojmuje, po co te zasady. jebać wszystko",
  "ja nie łapie, czemu tak trudno. jebać wszystkich",
  "ja nie ogarniam, po co tyle hałasu. jebać wszystko",
  "ja nie czaje, czemu to tak działa. jebać system",
  "ja nie rozumiem, o co wam chodzi. jebać zasady",
  "ja nie kumam, czemu to tak skomplikowane. jebać to wszystko",
  "ja nie pojmuje, po co te komplikacje. jebać wszystkich",
  "ja nie łapie, czemu tak dużo pytań. jebać życie",
  "ja nie ogarniam, czemu tak to działa. jebać system",
  "ja nie czaje, co to za problem. jebać zasady",
  "ja nie rozumiem, czemu tak trudno. jebać wszystko",
  "ja nie kumam, czemu tak dużo zasad. jebać wszystkich",
  "ja nie pojmuje, po co tyle komplikacji. jebać życie",
  "ja nie łapie, czemu tyle hałasu. jebać zasady",
  "ja nie ogarniam, czemu to tak ważne. jebać wszystko",
  "ja nie czaje, czemu to tak działa. jebać wszystkich",
  "ja nie rozumiem, czemu tyle problemów. jebać system",
  "ja nie kumam, czemu tyle pytań. jebać wszystko",
  "ja nie pojmuje, czemu to takie trudne. jebać wszystkich",
  "ja nie łapie, czemu to tak ważne. jebać życie",
  "ja nie ogarniam, czemu tak działa. jebać system",
  "ja nie czaje, czemu to taki problem. jebać zasady",
  "ja nie rozumiem, po co tyle pytań. jebać wszystko",
  "ja nie kumam, czemu tyle zasad. jebać wszystkich",
  "ja nie pojmuje, czemu tak trudno. jebać życie",
  "ja nie łapie, po co tyle problemów. jebać wszystko",
  "ja nie ogarniam, po co tyle komplikacji. jebać system",
  "ja nie czaje, po co te zasady. jebać zasady",
  "ja nie rozumiem, czemu to tak trudne. jebać wszystko",
  "ja nie kumam, po co tyle hałasu. jebać wszystkich",
  "ja nie pojmuje, czemu to tak działa. jebać życie",
  "ja nie łapie, czemu tyle pytań. jebać system",
  "ja nie ogarniam, czemu to takie ważne. jebać zasady",
  "ja nie czaje, po co tyle gadania. jebać wszystko",
  "ja nie rozumie, w szkole mnie uczyli tylko kilka komend. jebać psy btw",
];

export const generateObelga = () => {
  return Math.floor(Math.random() * obelgi.length);
};

export const generatePowiedzonko = () => {
  return Math.floor(Math.random() * ojciecJanuszZwroty.length);
};

export const generateNierozumie = () => {
  return Math.floor(Math.random() * nierozumie.length);
};
